{% set name = "pyccolo" %}
{% set version = "0.0.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyccolo-{{ version }}.tar.gz
  sha256: b03ba45444067e3fa08e58ebb9e758cead3b07db1c2f9d30e75c72ef50bed3b0

build:
  entry_points:
    - pyc = pyccolo.__main__:main
    - pyccolo = pyccolo.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=48
    - setuptools-git-versioning
    - wheel >=0.30.0
  run:
    - python >=3.7
    - traitlets
    - typing-extensions

test:
  imports:
    - pyccolo
  commands:
    - pip check
    - pyc --help
    - pyccolo --help
  requires:
    - pip

about:
  home: https://github.com/smacke/pyccolo
  summary: Declarative instrumentation for Python
  license: BSD-3-Clause
  license_file: docs/LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
