{% set name = "pyccolo" %}
{% set version = "0.0.51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyccolo-{{ version }}.tar.gz
  sha256: 90b5a525ba601ad07460dcc41595b318b1f16e5f66dfbc509719e96cba497c3d

build:
  entry_points:
    - pyc = pyccolo.__main__:main
    - pyccolo = pyccolo.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=48
    - setuptools-git-versioning
    - wheel >=0.30.0
  run:
    - python >=3.7
    - traitlets
    - typing-extensions

test:
  imports:
    - pyccolo
  commands:
    - pip check
    - pyc --help
    - pyccolo --help
  requires:
    - pip

about:
  home: https://github.com/smacke/pyccolo
  summary: Declarative instrumentation for Python
  license: BSD-3-Clause
  license_file: docs/LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
