{% set name = "pyccolo" %}
{% set version = "0.0.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyccolo-{{ version }}.tar.gz
  sha256: edeed470d1f1c45bd745e050d1c30344c7665d02da2815f5374284a1062d4fd6

build:
  entry_points:
    - pyc = pyccolo.__main__:main
    - pyccolo = pyccolo.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=48
    - setuptools-git-versioning
    - wheel >=0.30.0
  run:
    - python >={{ python_min }}
    - traitlets
    - typing_extensions

test:
  imports:
    - pyccolo
  commands:
    - pip check
    - pyc --help
    - pyccolo --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smacke/pyccolo
  summary: Declarative instrumentation for Python
  license: BSD-3-Clause
  license_file: docs/LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
